### ISSUE TITLE
Retrieving logs failed

### ISSUE THREAD

**Issue by jtheuer** [boxfuse/boxfuse-issues#145]
Hi, I use a custom policy for the boxfuse role to restrict access to our resources. I would like to be able to see the new logs feature for ```bofxuse run```. Currently I see:

```
Retrieving logs failed for i-xxxxxx : You are not authorized to perform this operation. (Service: AmazonEC2; Status Code: 403; Error Code: UnauthorizedOperation;
```

Which permission do I have to add to the boxfuse is needed to see the logs output? I tried
```
          Action:
          - ec2:Describe*
          - ec2:GetConsoleOutput
          Effect: Allow
          Resource: "*"
```
But that doesn't seem to be sufficient.

-Jan
