### ISSUE TITLE
Newrelic environment naming

### ISSUE THREAD

**Issue by jtheuer** [boxfuse/boxfuse-issues#68]
Hi,

Not sure if a bug or a missing configuration on my side:

I deployed my live app with boxfuse to aws but noticed that it is called "myapp-unknown" in the newrelic web view. I expected my custom environment suffix "-production".

How can I give it the right name?

Jan

**Comment by axelfontaine** [comment]
One technique you can use for this is to define different app names per environment in your newrelic.yml file:

```
common: &default_settings
  # Common config ...

dev:
  <<: *default_settings
  app_name: myapp-dev

test:
  <<: *default_settings
  app_name: myapp-test

prod:
  <<: *default_settings
  app_name: myapp-prod
```

And automatically selected the correct NewRelic environment with a JVM argument:
 `-jvm.args=-Dnewrelic.environment=$BOXFUSE_ENV`

Would this work for you?
